# Generated by Django 5.1.8 on 2026-06-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('series', models.CharField(blank=True, help_text='Model series, e.g. "NXB-63", "T MAX", "HDM3"', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='One-line description for cards and search results')),
                ('full_description', models.TextField(blank=True, help_text='Detailed product description for the detail page')),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('datasheet_url', models.URLField(blank=True, help_text='Link to PDF datasheet')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured products section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (auto-generated if blank)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (auto-generated if blank)', max_length=160)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.CharField(blank=True, help_text='Catalog/model number', max_length=100)),
                ('description', models.CharField(help_text='Variant description, e.g. "16A 3-Pole IP44"', max_length=300)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in PKR (leave blank if price on request)', max_digits=12, null=True)),
                ('price_on_request', models.BooleanField(default=False, help_text='Check if price is "POR" or "On Request"')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Flexible specs: {"ampere": "32A", "poles": "3", "breaking_capacity": "6kA"}')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
