# Generated by Django 5.1.8 on 2026-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction / reference number quoted by the customer', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=models.FileField(blank=True, help_text='Screenshot or photo of the bank transfer receipt', upload_to='payment_slips/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_slip_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
