# Generated by Django 5.1.8 on 2026-07-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text="The customer's own message with the request")),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes — never exposed to the customer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('product', 'Product Page'), ('cart', 'Cart RFQ'), ('whatsapp', 'WhatsApp'), ('contact', 'Contact Form')], default='product', max_length=20)),
                ('quoted_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('variant_description', models.CharField(blank=True, default='', max_length=300)),
                ('cat_no', models.CharField(blank=True, default='', max_length=100)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price the sales team quotes for this line (blank = not yet quoted)', max_digits=12, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
