# Generated by Django 5.1.8 on 2026-06-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name, e.g. "MCBs" for "Miniature Circuit Breakers"', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class name', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('color', models.CharField(blank=True, help_text='Hex color code for UI, e.g. #F97316', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
