# Generated by Django 5.1.8 on 2026-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='admin_reply',
            field=models.TextField(blank=True, default='', help_text='Reply sent to the customer (visible to them)'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
