# Generated by Django 5.1.8 on 2026-06-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
                ('origin_country', models.CharField(blank=True, help_text='Country of origin, e.g. "Switzerland", "Turkey"', max_length=100)),
                ('supplier_name', models.CharField(blank=True, help_text='Local supplier/distributor, e.g. "AT Electricals"', max_length=200)),
                ('supplier_contact', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Brand accent color hex, e.g. #FF0000 for ABB', max_length=7)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
