# Generated by Django 5.1.8 on 2026-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carousel', 'Hero Carousel'), ('sidebar', 'Sidebar Promo')], default='carousel', help_text='Where this banner is displayed on the homepage', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('badge', models.CharField(blank=True, help_text='Small label above the title, e.g. "PREMIUM SELECTION"', max_length=100)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.CharField(blank=True, max_length=500)),
                ('cta_text_2', models.CharField(blank=True, max_length=100)),
                ('cta_link_2', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL, used when no image file is uploaded', max_length=1000)),
                ('accent_color', models.CharField(blank=True, default='#3B82F6', max_length=7)),
                ('text_color', models.CharField(blank=True, default='#FFFFFF', max_length=7)),
                ('bg_color', models.CharField(blank=True, default='#0F172A', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'order', 'id'],
            },
        ),
    ]
