# Generated by Django 5.1.8 on 2026-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of short strings shown as pills under the hero text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.CharField(blank=True, help_text='Background video for the homepage hero, e.g. /herovideo.mp4 or a full URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('hero', 'Homepage Hero'), ('carousel', 'Hero Carousel'), ('sidebar', 'Sidebar Promo')], default='carousel', help_text='Where this banner is displayed on the homepage', max_length=20),
        ),
    ]
