# Generated by Django 5.1.8 on 2026-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Eng-Mart', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('mobile', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('hours', models.CharField(blank=True, default='', max_length=200)),
                ('hours_note', models.CharField(blank=True, default='', max_length=200)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('map_embed_url', models.URLField(blank=True, default='', max_length=1000)),
                ('map_link_url', models.URLField(blank=True, default='', max_length=1000)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=500)),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('twitter_url', models.URLField(blank=True, default='', max_length=500)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('bank_transfer_enabled', models.BooleanField(default=True)),
                ('mobile_wallet_enabled', models.BooleanField(default=False)),
                ('whatsapp_order_enabled', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_title', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=64)),
                ('bank_iban', models.CharField(blank=True, default='', max_length=34)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=200)),
                ('bank_swift', models.CharField(blank=True, default='', max_length=16)),
                ('bank_name_2', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_title_2', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number_2', models.CharField(blank=True, default='', max_length=64)),
                ('bank_iban_2', models.CharField(blank=True, default='', max_length=34)),
                ('bank_branch_2', models.CharField(blank=True, default='', max_length=200)),
                ('bank_transfer_note', models.TextField(blank=True, default='')),
                ('jazzcash_number', models.CharField(blank=True, default='', max_length=50)),
                ('jazzcash_title', models.CharField(blank=True, default='', max_length=200)),
                ('easypaisa_number', models.CharField(blank=True, default='', max_length=50)),
                ('easypaisa_title', models.CharField(blank=True, default='', max_length=200)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('footer_payment_note', models.CharField(blank=True, default='', max_length=300)),
                ('copyright_text', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
